Exp - 1 merge testing to main
virtual-labs/exp-transistor-level-inverter-iiith pull request #9
Opened 2022-04-05 11:05 UTC by srisatyavinay

2022-04-05 12:06 UTC, vjspranav requested changes

2022-04-05 12:06 UTC, vjspranav commented on experiment/simulation/js/nand.js
> +        list_input[0].input = 0
you could probably use ternary here single liners
```
list_input[0] = x ? 0 : 1;
```

2022-04-05 12:06 UTC, vjspranav commented on experiment/simulation/js/nand.js
> +function norvalidate() {
norvalidate and nandvalidate look exactly the same to me, could you clarify if there is any difference.

2022-04-05 12:06 UTC, vjspranav commented on experiment/simulation/js/nand.js
> +    if(x == true && y == true)
these are booleans you don't have to do ```== true```,
I would prefer it like ```if(x && y)```

and you can decrease number of conditions here like
```list_ouput[0].voltage = x==y ?  -5 : 5```
this will take care of all cases

2022-04-07 10:01 UTC, srisatyavinay commented on experiment/simulation/index.html
> +        var list_pmos = [];
Replaced var with let or const

2022-04-07 10:11 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +// This function checks map when called
- Removed function reload
- Removed unnecessary console.log
- > In function circuitvalid, in each condition the last two statements are redundant. Don't replicate code there, remove them out of the if condition.
    I think they are required so did not remove it. Can you clarify on it?

2022-04-07 10:40 UTC, srisatyavinay commented on experiment/simulation/index.html
> +        var list_pmos = [];
Replaced var with const or let

2022-04-07 10:44 UTC, srisatyavinay commented on experiment/simulation/js/nand.js
> +function norvalidate() {
These functions are not for this experiment. I removed them now.

2022-04-07 10:44 UTC, srisatyavinay commented on experiment/simulation/js/nand.js
> +    if(x == true && y == true)
This part is removed

2022-04-07 11:05 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +var instance = jsPlumb.getInstance({
- Removed debugging statements
- Replaced var with const/let
- Made a new function `addinstance` and called that function in all the remaining functions.

2022-04-07 12:00 UTC, vjspranav commented on experiment/simulation/js/circuit.js
> +// This function checks map when called
About circuitValidate, I was wrong it is fine.

2022-04-08 12:03 UTC, raj-vlabs requested changes
Major improvements required. I am also not happy with the approach followed for evaluating the circuit but I need to think more about it before I give my comments.
Meanwhile please review your whole code hard for the comments provided.
I have not put a comment at every single instance of a violation so please fix all instances where the comment would be applicable.

2022-04-08 12:03 UTC, raj-vlabs commented on experiment/simulation/js/components.js
> +let count1 = 0;
Where are these count variables used and what do they mean to count? Is it possible to use an array with an Enum to refer to the index, e.g. count[PMOS], count[NMOS] etc?

2022-04-08 13:54 UTC, rohankatha commented on experiment/simulation/css/main.css
> +#diagram .input_component1 {
We resolved it sir

2022-04-09 16:20 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +#diagram .input_component1 {
Replaced `input_component1`, `input_component2`, `output_component` with `io-component`

2022-04-09 16:20 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +  border-radius: 10px;
Replaced px with rem everywhere

2022-04-09 16:24 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +#diagram .input_component2 {
Replaced `input_component1`, `input_component2`, `output_component` with `io-component`

2022-04-09 16:24 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +#diagram .HIGH {
Changed HIGH, LOW to high, low

2022-04-09 16:24 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +const instance = jsPlumb.getInstance({
Renamed instance to jsplumbInstance

2022-04-09 16:26 UTC, rohankatha commented on experiment/simulation/js/components.js
> +	let con = instance.getAllConnections();
Declared con as const

2022-04-09 16:31 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +instance.bind("connection", function (ci) {
The `ci` argument is not required. It is removed. Each time a connection is made the old `connection_map` is cleared and remade with this function.

2022-04-09 16:31 UTC, srisatyavinay commented on experiment/simulation/index.html
> +		const jsmap = new Map();
Renamed `jsmap` to `connection_map`

2022-04-09 16:32 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +function checkandupdate() {
Converted all function and variable names to camel case

2022-04-09 16:32 UTC, srisatyavinay commented on experiment/simulation/index.html
> +		let list_inverter = [];
Changed let to const

2022-04-09 16:55 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	let results = [];
It is const. It is now changed

2022-04-09 16:56 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +function check_pseudo_nmos() {
Converted all variable names into camelCase

2022-04-09 16:58 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	else if (selected_tab == 1 && ps_nmos_circuit_valid) {
It is not a global variable and a function is used to return it's value

2022-04-09 16:58 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +		document.getElementById("output-box").innerHTML = "&#10060; Circuit is incorrect"
Created a separate function

2022-04-09 16:59 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	// change input signal
This function is not required. It is removed now

2022-04-09 17:00 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	out = list_ouput[0].voltage
Indentation is fixed

2022-04-09 17:01 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	ps_nmos_circuit_valid = 0
Added let before it

2022-04-09 17:37 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +			permute(arr.slice(), memo.concat(cur));
Yes it is used to make a copy of array

2022-04-09 17:42 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	if (selected_tab == 0 && jsmap.has("vdd0$pmos0") && jsmap.has("input0$pmos0") && jsmap.has("pmos0$output0") && jsmap.has("input0$nmos0") && jsmap.has("nmos0$output0") && jsmap.has("ground0$nmos0"))
Used ===

2022-04-09 17:45 UTC, srisatyavinay commented on experiment/simulation/index.html
> +				<div class="v-datalist-row text-danger" id="error-container" style="display:none !important;">
Removed !important. It is not required.

2022-04-12 21:19 UTC, srisatyavinay commented on experiment/simulation/index.html
> +		let selected_tab = 0
We used Enum for tab selection

2022-04-12 21:20 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +let count1 = 0;
We used enums now

2022-04-13 02:38 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +/*instance.bind("click", function (conn) {
Removed dead code

2022-04-15 13:13 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +	for (i = 0; i < list_vdd.length; i++) {
We want to leave them as for loop only since it will take a lot of time to change everything in all files

2022-04-15 13:14 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +        return "1"
If output is disconnected in such cases, we have put it as `-`

2022-04-19 06:03 UTC, raj-vlabs requested changes
Overall much improved code, I appreciate the effort and the quality. Following issues need to be fixed:
1. JS files still do not have the strict mode enabled
2. Template literals should be used to concatenate string requiring variable evaluation.
3. Please use descriptive names for variables, do not use names like k, d etc
4. Please only keep debug logs in the code, remove all other logging from production code

2022-04-19 06:03 UTC, raj-vlabs commented on experiment/simulation/js/not.js
> +    document.getElementById("output-box").innerHTML = htmlText
Instead of repeating the logic to get the element, please store the element in a const and then use it:
const observationBoxElem = document.getElementById("output-box");
observationBoxElem.innerHTML = htmlText;
observationBoxElem.classList.toggle(removedClass);
observationBoxElem.classList.toggle(addedClass);

You can consider passing a list of classnames to be toggled in place of taking remove and add classes separately. Then you can run through the list toggling each one:

toggleClasses.forEach(class => observationBoxElem.classList.toggle(class))

2022-04-19 06:55 UTC, raj-vlabs requested changes
One more refactor required.
Please improve the readability of the code by using descriptive variable names.

2022-04-19 06:55 UTC, raj-vlabs commented on experiment/simulation/js/components.js
> +    const con = jsplumbInstance.getAllConnections();
Please refactor using forEach here.

jsplumbInstance.getAllConnections().forEach(connection => {
const connectionId = `${connection.sourceId}$${connection.targetId}`
connectionMap.set(connectionId, connection.targetId)
});

2022-04-19 17:32 UTC, srisatyavinay commented on experiment/simulation/index.html
> +	<script src="https://cdn.jsdelivr.net/gh/virtual-labs/virtual-style@0.0.8-b/js/script.js"></script>
This is javascript and the one above is css

2022-04-19 19:41 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +    min-height: 2.96875rem;
Max precision is now kept upto decimal points

2022-04-19 19:41 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +  #diagram .component2 {
It is for other experiments. Now removed

2022-04-19 19:41 UTC, srisatyavinay commented on experiment/simulation/index.html
> +					<!-- <div class="toolbar-component" onclick="jinput()">
Removed it.

2022-04-19 19:42 UTC, srisatyavinay commented on experiment/simulation/index.html
> +	<script>
It is very difficult to categorise all files into a js module right now due to lack of time.

2022-04-19 19:42 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +function checkAndUpdate() {
Now used strict mode

2022-04-19 19:42 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +                    console.log("Pmos disabled");
Removed them.

2022-04-19 19:42 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +
Removed them.

2022-04-19 19:42 UTC, srisatyavinay commented on experiment/simulation/js/circuit.js
> +    console.log(listOutput[0].voltage)
Removed dead code

2022-04-19 19:42 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +// top -> [0.5, 0, 0, -1]
Removed dead code

2022-04-19 19:43 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +function compPmos() {
Used strict mode

2022-04-19 19:43 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +    const d1 = new Object();
Changed them.

2022-04-19 19:44 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +    const d = document.createElement('div');
That is again to difficult to change now due to lack of time. Some of them require some of the things and some don't, so it is not possible now.

2022-04-19 19:44 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +    const id = "pmos" + count.PMOS;
Used them.

2022-04-19 19:44 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +    const d1 = new Object();
As said above that is again to difficult to change now due to lack of time. Some of them require some of the things and some don't, so it is not possible now.

2022-04-19 19:44 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +        k = document.getElementById("input0")
Used descriptive names.

2022-04-19 19:45 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +            k.classList.remove("high")
It doesn't work in some cases like for the first time both needs to be added etc. So did not change it.

2022-04-19 19:50 UTC, srisatyavinay commented on experiment/simulation/js/not.js
> +function notValid() {
Used it now.

2022-04-19 19:50 UTC, srisatyavinay commented on experiment/simulation/js/not.js
> +    // document.getElementById('error-container').style.display='flex'
Removed it now.

2022-04-19 19:50 UTC, srisatyavinay commented on experiment/simulation/js/not.js
> +    k = document.getElementById("input0")
Changed them into descriptive names

2022-04-19 19:50 UTC, srisatyavinay commented on experiment/simulation/js/not.js
> +        console.log("In low")
Removed it.

2022-04-19 19:53 UTC, srisatyavinay commented on experiment/simulation/js/not.js
> +    a.innerHTML = "<tr><td>0</td><td>1</td><td>" + output[0] + "</td></tr>" + "<tr><td>1</td><td>0</td><td>" + output[1] + "</td></tr>"
Used them.

2022-04-19 19:53 UTC, srisatyavinay commented on experiment/simulation/js/not.js
> +    document.getElementById("output-box").innerHTML = htmlText
Used them now.

2022-04-19 19:57 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +! function(e, t) {
https://stackoverflow.com/a/44459945
We used this link to do that.

2022-04-19 20:02 UTC, srisatyavinay commented on experiment/simulation/js/integrate.js
> +    d.midterminal = 1;
Changed them

2022-04-19 20:35 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +    const con = jsplumbInstance.getAllConnections();
Changed it.

2022-04-19 20:41 UTC, srisatyavinay commented
Made the changes suggested in all the experiments.

2022-07-18 14:57 UTC, raj-vlabs requested changes
1. Please remove the files which are not needed like experiment/images/option_exp1.png

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/pretest.json
> +        "question": " 4. The output and input impedance of a CMOS inverter are>",
Please remove the > from the end of the question

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/pretest.json
> +        "question": "6. Which of the following are desired characteristics in a CMOS inverter <img src='images/option_exp1.png>",
Why do we need to embed an image for these options? We can just list them and get rid of the image.

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/procedure.md
> +* On clicking "validate" option after completing the circuit (assumin g all connections are done correctly) you should see a table on the right side of the workspace
Please remove the extra space from 'assumin g'

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/cmos-demo.html
> +    <div class="columns is-centered is-flex is-flex-direction-row is-flex-wrap-wrap is-align-content-start">
Please remove is-flex. It is not needed with columns

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/css/demo.css
> +.threeipnand {
It'd be better to hyphenate the name to make it readable like:
three-ip-nand

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/css/demo.css
> +  float: right;
Please prefer to use flexbox for floating behavior. float is not used in modern CSS much

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/index.html
> +    <div class="columns mt-2 is-variable is-1 is-centered is-flex is-flex-wrap-wrap">
is-flex is not needed with columns

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/animation-cmos.js
> +    }
Please have a default else clause. In this case it can be used to log an error because it is not an expected state

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/animation-cmos.js
> +    else if (decide) {
Do we need to check the value of decide again inside the else block?

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/animation-cmos.js
> +    if (timeline.time() !== 0 && timeline.progress() !== 1) {
Do we need to check timeline.time() also or just timeline.progress() is sufficient?

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/animation-cmos.js
> +    else if (timeline.progress() === 1) {
Please add a default else clause.

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/animation-nmos.js
> +    else if (decide) {
Do we need to again check the value of decide in else block?

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listPmos.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listPmos.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listNmos.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listPmos.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listNmos.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listOutput.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listOutput.length; j++) {
Both these for loops can be converted to for..of loops

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/integrate.js
> +    svgElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-0.5 -0.5 84 84" ><g><path d="M 31 61 L 31 21" fill="none" stroke
Can this be made a bit more readable?

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/integrate.js
> +    const divPushed = new Object();
Prefer to use object literals { } in place of Object class for performance reasons.

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/integrate.js
> +    const svgElement = document.createElement('div');
Please try to make it more readable

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/integrate.js
> +    const divPushed = new Object();
Prefer object literals { } over Object class

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/integrate.js
> +    const svgElement = document.createElement('div');
Please try to make it more readable

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/integrate.js
> +}(window, document);
Line 224 - 268, has this code been used anywhere? If not, please delete it. It has been lifted from some library with no clear understanding of what it does

2022-07-18 14:57 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    listOutput.length = 0;
Is it better to reassign these lists to empty lists [  ]  rather than setting the lengths to 0?

2022-07-19 10:49 UTC, Aditya-debug15 commented on experiment/simulation/js/main.js
> +    listOutput.length = 0;
Changed to empty list now

2022-07-19 11:17 UTC, Aditya-debug15 commented on experiment/simulation/js/integrate.js
> +}(window, document);
yes removed that

2022-07-19 11:18 UTC, Aditya-debug15 commented on experiment/simulation/js/integrate.js
> +    const svgElement = document.createElement('div');
Just moved it to new lines, added classes and added indentation, looks like a HTML block now.

2022-07-19 11:19 UTC, Aditya-debug15 commented on experiment/simulation/js/integrate.js
> +    const divPushed = new Object();
changed it

2022-07-19 11:19 UTC, Aditya-debug15 commented on experiment/simulation/js/integrate.js
> +    const svgElement = document.createElement('div');
Just moved it to new lines, added classes and added indentation, looks like a HTML block now.

2022-07-19 11:19 UTC, Aditya-debug15 commented on experiment/simulation/js/integrate.js
> +    const divPushed = new Object();
changed it

2022-07-19 11:19 UTC, Aditya-debug15 commented on experiment/simulation/js/integrate.js
> +    svgElement.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-0.5 -0.5 84 84" ><g><path d="M 31 61 L 31 21" fill="none" stroke
Just moved it to new lines, added classes and added indentation, looks like a HTML block now.

2022-07-19 11:19 UTC, gautamxyz commented on experiment/pretest.json
> +        "question": "1. In inverter circuits what would be a preferred load? ",
Removed

2022-07-19 11:20 UTC, gautamxyz commented on experiment/pretest.json
> +        "question": "3. How many regions of operation does a CMOS inverter has?>",
Removed

2022-07-19 11:20 UTC, Aditya-debug15 commented on experiment/simulation/js/animation-nmos.js
> +    else if (decide) {
changed it

2022-07-19 11:20 UTC, Aditya-debug15 commented on experiment/simulation/js/animation-cmos.js
> +    else if (timeline.progress() === 1) {
added

2022-07-19 11:20 UTC, gautamxyz commented on experiment/pretest.json
> +        "question": " 4. The output and input impedance of a CMOS inverter are>",
Removed

2022-07-19 11:21 UTC, gautamxyz commented on experiment/pretest.json
> +        "question": "6. Which of the following are desired characteristics in a CMOS inverter <img src='images/option_exp1.png>",
Removed the question

2022-07-19 11:21 UTC, gautamxyz commented on experiment/procedure.md
> +* On clicking "validate" option after completing the circuit (assumin g all connections are done correctly) you should see a table on the right side of the workspace
Removed

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listPmos.length; j++) {
Changed to for..of

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listPmos.length; j++) {
Changed to for..of

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listNmos.length; j++) {
Changed to for..of

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listNmos.length; j++) {
Changed to for..of

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listPmos.length; j++) {
Changed to for..of

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listNmos.length; j++) {
Changed to for..of

2022-07-19 11:22 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listOutput.length; j++) {
Changed to for..of

2022-07-19 11:23 UTC, gautamxyz commented on experiment/simulation/js/circuit.js
> +        for (let j = 0; j < listOutput.length; j++) {
Changed to for..of

2022-07-19 11:23 UTC, Aditya-debug15 commented on experiment/simulation/js/animation-cmos.js
> +    if (timeline.time() !== 0 && timeline.progress() !== 1) {
It is kept as a precaution but since it is not needed we removed that

2022-07-19 11:24 UTC, gautamxyz commented on experiment/simulation/index.html
> +    <div class="columns mt-2 is-variable is-1 is-centered is-flex is-flex-wrap-wrap">
Removed

2022-07-19 11:24 UTC, gautamxyz commented on experiment/simulation/cmos-demo.html
> +    <div class="columns is-centered is-flex is-flex-direction-row is-flex-wrap-wrap is-align-content-start">
Removed

2022-07-19 11:24 UTC, Aditya-debug15 commented on experiment/simulation/js/animation-cmos.js
> +    else if (decide) {
it was not needed so we removed that

2022-07-19 11:25 UTC, Aditya-debug15 commented on experiment/simulation/index.html
> +    <div class="columns mt-2 is-variable is-1 is-centered is-flex is-flex-wrap-wrap">
apology we didn't see that earlier removed now

2022-07-19 11:25 UTC, Aditya-debug15 commented on experiment/simulation/cmos-demo.html
> +    <div class="columns is-centered is-flex is-flex-direction-row is-flex-wrap-wrap is-align-content-start">
apology we didn't see that earlier removed now

2022-07-19 11:26 UTC, Aditya-debug15 commented on experiment/simulation/css/demo.css
> +.threeipnand {
We just copied demo.css from dld since these components are not present in vlsi we removed the dead code

2022-07-19 11:26 UTC, Aditya-debug15 commented on experiment/simulation/css/demo.css
> +  float: right;
We just copied demo.css from dld since these components are not present in vlsi we removed the dead code

2022-07-22 09:28 UTC, raj-vlabs approved these changes

2022-07-22 09:28 UTC, merged